[package]
name = "fdupes"
version = "0.1.0"
authors = ["SMartinScottLogic <smartin@scottlogic.com>"]
edition = "2018"

[dependencies]
log = "^0.3"
env_logger = "^0.3"
walkdir = "2"
crc = "1.8.1"            # Rust implementation of CRC(16, 32, 64) with support of various standards
